
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Non_Registrated.java
 *
 * Created on Jun 5, 2018, 10:32:24 AM
 */
/**
 *
 * @author Prajapati
 */
public class Non_Registrated extends javax.swing.JFrame {

    /** Creates new form Non_Registrated */
    public Non_Registrated() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Cpl2 = new javax.swing.JButton();
        Ph3 = new javax.swing.JTextField();
        PIN2 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ad2 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        NmC1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setUndecorated(true);

        jLabel1.setFont(new java.awt.Font("LCD", 0, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Non-Registered Complain");

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel2.setForeground(new java.awt.Color(255, 204, 204));
        jLabel2.setText("Complain issued by :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(110, 90, 216, 25);

        jLabel3.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel3.setForeground(new java.awt.Color(255, 204, 204));
        jLabel3.setText("Address");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(110, 230, 84, 25);

        jLabel4.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel4.setForeground(new java.awt.Color(255, 204, 204));
        jLabel4.setText("PIN");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(110, 130, 31, 25);

        jLabel5.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel5.setForeground(new java.awt.Color(255, 204, 204));
        jLabel5.setText("Phone No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(110, 170, 94, 25);

        Cpl2.setFont(new java.awt.Font("LCD", 0, 24));
        Cpl2.setText("Complain");
        Cpl2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cpl2ActionPerformed(evt);
            }
        });
        jPanel1.add(Cpl2);
        Cpl2.setBounds(220, 350, 200, 33);

        Ph3.setFont(new java.awt.Font("LCD", 0, 18));
        Ph3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ph3ActionPerformed(evt);
            }
        });
        Ph3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ph3KeyTyped(evt);
            }
        });
        jPanel1.add(Ph3);
        Ph3.setBounds(360, 180, 430, 25);

        PIN2.setFont(new java.awt.Font("LCD", 0, 18));
        PIN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN2ActionPerformed(evt);
            }
        });
        PIN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PIN2KeyTyped(evt);
            }
        });
        jPanel1.add(PIN2);
        PIN2.setBounds(360, 130, 430, 25);

        Ad2.setColumns(20);
        Ad2.setFont(new java.awt.Font("LCD", 0, 18));
        Ad2.setRows(5);
        Ad2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ad2KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(Ad2);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 220, 430, 101);

        jButton2.setFont(new java.awt.Font("LCD", 0, 24));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(540, 350, 130, 33);

        NmC1.setFont(new java.awt.Font("LCD", 0, 18));
        NmC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NmC1ActionPerformed(evt);
            }
        });
        NmC1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NmC1KeyTyped(evt);
            }
        });
        jPanel1.add(NmC1);
        NmC1.setBounds(360, 90, 430, 25);

        jButton3.setFont(new java.awt.Font("LCD", 0, 24));
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(730, 350, 110, 33);

        jLabel6.setFont(new java.awt.Font("LCD", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__abstergo___by_0blackcell-d46zmul.jpg"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(0, 0, 1040, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addComponent(jLabel1)
                .addContainerGap(393, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1038)/2, (screenSize.height-495)/2, 1038, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Main().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void Cpl2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cpl2ActionPerformed
        String Name = NmC1.getText();             // Entering Name , PIN, Phone, Address by USER
        String PIN = PIN2.getText();
        String Ph = Ph3.getText();
        String Add = Ad2.getText();

        if (Name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name not Entered");
        } else if (Add.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address not Entered");
        } else if (PIN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "PIN not Entered");
        } else if (Ph.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ph not Entered");
        } else {
            try {                                                       // Getting connection with non_register table in mysql
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
                String query = "INSERT INTO non_Register VALUES('" + Name + "','" + Ph + "','" + Add + "','" + PIN + "');";
                stmt.executeUpdate(query);
                this.setVisible(false);
                new Non_RComplain(Ph).setVisible(true);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Please, Enter appropiate detail in appropiate field.");
                NmC1.setText("");
                PIN2.setText("");
                Ad2.setText("");
                Ph3.setText("");

            }
        }




    // TODO add your handling code here:
    }//GEN-LAST:event_Cpl2ActionPerformed

    private void NmC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NmC1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NmC1ActionPerformed

    private void NmC1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NmC1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NmC1KeyTyped

    private void PIN2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PIN2KeyTyped
        boolean max = PIN2.getText().length() > 5;
        if (max) {
            evt.consume();
        }        // Limits the Maximum input upto 6 only.
    }//GEN-LAST:event_PIN2KeyTyped

    private void Ph3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ph3KeyTyped
        boolean max = Ph3.getText().length() > 9;
        if (max) {
            evt.consume();
        }        // Limits the Maximum input upto 10 only.
    }//GEN-LAST:event_Ph3KeyTyped

    private void Ad2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ad2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_Ad2KeyTyped

    private void PIN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PIN2ActionPerformed

    private void Ph3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ph3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ph3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        NmC1.setText("");                   // Clear all the respective Fields.
        PIN2.setText("");
        Ad2.setText("");
        Ph3.setText("");




    // TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Non_Registrated().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Ad2;
    private javax.swing.JButton Cpl2;
    private javax.swing.JTextField NmC1;
    private javax.swing.JTextField PIN2;
    private javax.swing.JTextField Ph3;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
