
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Non_User_Login.java
 *
 * Created on Sep 29, 2018, 12:38:52 PM
 */
/**
 *
 * @author Prajapati
 */
public class Non_User_Login extends javax.swing.JFrame {

    private String other2;

    /** Creates new form Non_User_Login */
    public Non_User_Login() {
        initComponents();
    }

    public Non_User_Login(String Transfer1) {
        initComponents();
        Ph1.setText(Transfer1);                         // Retrive Phone No from USER
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        PASS = new javax.swing.JPasswordField();
        ID = new javax.swing.JTextField();
        Ph1 = new javax.swing.JTextField();
        Ph2 = new javax.swing.JTextField();
        t1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("LCD", 0, 36));
        jLabel1.setForeground(new java.awt.Color(102, 255, 204));
        jLabel1.setText("ID ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 170, 160, 40);

        jLabel2.setFont(new java.awt.Font("LCD", 0, 36));
        jLabel2.setForeground(new java.awt.Color(102, 255, 204));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(90, 250, 180, 30);

        jButton2.setFont(new java.awt.Font("LCD", 0, 36));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(650, 433, 120, 40);

        jButton1.setFont(new java.awt.Font("LCD", 0, 36));
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(260, 323, 190, 60);

        PASS.setFont(new java.awt.Font("LCD", 0, 18));
        PASS.setDoubleBuffered(true);
        PASS.setEchoChar('*');
        jPanel1.add(PASS);
        PASS.setBounds(280, 250, 280, 30);

        ID.setFont(new java.awt.Font("LCD", 0, 36));
        jPanel1.add(ID);
        ID.setBounds(280, 170, 280, 30);
        jPanel1.add(Ph1);
        Ph1.setBounds(150, 460, 130, 20);
        jPanel1.add(Ph2);
        Ph2.setBounds(10, 460, 120, 20);
        jPanel1.add(t1);
        t1.setBounds(270, 330, 6, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("LCD", 0, 48));
        jLabel4.setForeground(new java.awt.Color(0, 255, 153));
        jLabel4.setText("FOR OFFICERS USE ONLY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(200, 40, 500, 49);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__abstergo___by_0blackcell-d46zmul.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 1060, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1038)/2, (screenSize.height-495)/2, 1038, 495);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Main().setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Id = ID.getText();
        String detail = Ph1.getText();
        int Dl = detail.length();
        String Name = "";
        String PIN = "";
        String Address = "";
        String M = "", n = "";

        for (int i = 1; i <= 10; ++i) {
            String C = detail.substring(i - 1, i);
            M = M + C;
        }
        String RunRs = detail.substring(Dl - 1);
        Ph2.setText(M);
        for (int j = 11; j <= Dl; ++j) {
            String D = detail.substring(j - 1, j);
            n = n + D;
        }
        detail = M + '\n' + n;
        String Ph = Ph2.getText();
       
        if (RunRs.equals("1")) {                                // Getting Connection with a_register table.
            try {
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
                String query = "SELECT * FROM a_register WHERE phone='" + Ph + "';";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.next()) {
                    Name = rs.getString("name");
                    PIN = rs.getString("Pin");
                    Address = rs.getString("Address");
                    t1.setText(PIN);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } else {
            try {                                                       // Getting Connection with non_register table.
                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
                String query = "SELECT * FROM non_register WHERE phone='" + Ph + "';";
                ResultSet rs = stmt.executeQuery(query);
                if (rs.next()) {
                    Name = rs.getString("name");
                    PIN = rs.getString("Pin");
                    Address = rs.getString("Address");
                    t1.setText(PIN);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        } String send2 = "Name :" + Name + '\n' + "Address :" + Address + '\n' + "Pin:-" + PIN + '\n' + "Ph:-" + detail;
        String PIN1 = t1.getText();
         String P = new String(PASS.getPassword());

            if (P.equals("12345") && (Id.equals("rakesh sharma") || Id.equals("RAKESH SHARMA"))) {
            if (PIN1.equals("395010")) {
                    try {                                                   // Getting Connection with report table.

                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
                String query1 = "INSERT INTO report VALUES('" + Name + "','" + Address + "','" +PIN   + "','" +M + "','" + n + "','" + Id + "');";
                stmt.executeUpdate(query1);
                            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());

            }
                    this.setVisible(false);
                new Non_User_Report(send2).setVisible(true);
            } else {
                this.setVisible(false);
                new Non_User_Report().setVisible(true);
            }
            } else if (P.equals("12345") && (Id.equals("SARTAJ SINGH") || Id.equals("satraj singh"))) {
            if (PIN1.equals("500000")) { try {

                Class.forName("java.sql.DriverManager");                        // Getting Connection with report table.
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
                String query1 = "INSERT INTO report VALUES('" + Name + "','" + Address + "','" +PIN   + "','" +M + "','" + n + "','" + Id + "');";
                stmt.executeUpdate(query1);
                            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                            }
                this.setVisible(false);
                new Non_User_Report(send2).setVisible(true);
            } else {
                this.setVisible(false);
                new Non_User_Report().setVisible(true);
            }
            }else if (P.equals("12345") && (Id.equals("GOPAL GAITONDE") || Id.equals("gopal gaitonde"))) {
            if (PIN1.equals("395001")) {
                try {

                Class.forName("java.sql.DriverManager");                    // Getting Connection with report table.
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
                String query1 = "INSERT INTO report VALUES('" + Name + "','" + Address + "','" +PIN   + "','" +M + "','" + n + "','" + Id + "');";
                stmt.executeUpdate(query1);
                            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                            }
                this.setVisible(false);
                new Non_User_Report(send2).setVisible(true);
            } else {
                this.setVisible(false);
                new Non_User_Report().setVisible(true);
            }
            }else if (P.equals("abstergo12345") && (Id.equals("ACP PRADHYUMAN") || Id.equals("acp pradhyuman"))) {

              this.setVisible(false);
                new Report().setVisible(true);


            }




         else if (P.equals("12345") && (Id.equals("SHINGHAM SIKRE") || Id.equals("shingham sikre"))) {
            if (PIN1.equals("400001")) {
            try {

                Class.forName("java.sql.DriverManager");            // Getting Connection with report table.
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
            String query1 = "INSERT INTO report VALUES('" + Name + "','" + Address + "','" +PIN   + "','" +M + "','" + n + "','" + Id + "');";
                stmt.executeUpdate(query1);
                            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                            }
            this.setVisible(false);
                new Non_User_Report(send2).setVisible(true);
            } else {
                this.setVisible(false);
                new Non_User_Report().setVisible(true);
            }
        }
        else {JOptionPane.showMessageDialog(null, "WRONG PASSWORD");
            ID.setText("");
            PASS.setText("");}
        



     
           


        System.out.print(PIN1);


 
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        t1.setVisible(false);
        Ph1.setVisible(false);
        Ph2.setVisible(false);
/// TODO add your handling code here:
    /// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Non_User_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JPasswordField PASS;
    private javax.swing.JTextField Ph1;
    private javax.swing.JTextField Ph2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables
}
