
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Register.java
 *
 * Created on Jun 5, 2018, 10:27:06 AM
 */
/**
 *
 * @author Prajapati
 */
public class Register extends javax.swing.JFrame {

    /** Creates new form Register */
    public Register() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nm2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        PIN1 = new javax.swing.JTextField();
        Ph2 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Ad1 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel1.setForeground(new java.awt.Color(51, 255, 204));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(150, 80, 48, 25);

        jLabel2.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel2.setForeground(new java.awt.Color(51, 255, 204));
        jLabel2.setText("Pin");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 170, 31, 25);

        jLabel3.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel3.setForeground(new java.awt.Color(51, 255, 204));
        jLabel3.setText("Phone No.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 120, 94, 25);

        Nm2.setFont(new java.awt.Font("LCD", 0, 18));
        Nm2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jPanel1.add(Nm2);
        Nm2.setBounds(270, 80, 340, 25);

        jButton1.setFont(new java.awt.Font("LCD", 0, 24));
        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 350, 150, 33);

        jButton2.setFont(new java.awt.Font("LCD", 0, 24));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(730, 350, 100, 33);

        PIN1.setFont(new java.awt.Font("LCD", 0, 18));
        PIN1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        PIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIN1ActionPerformed(evt);
            }
        });
        PIN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PIN1KeyTyped(evt);
            }
        });
        jPanel1.add(PIN1);
        PIN1.setBounds(270, 160, 340, 30);

        Ph2.setFont(new java.awt.Font("LCD", 0, 18));
        Ph2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ph2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ph2KeyTyped(evt);
            }
        });
        jPanel1.add(Ph2);
        Ph2.setBounds(270, 120, 340, 30);

        jButton3.setFont(new java.awt.Font("LCD", 0, 24));
        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(610, 350, 110, 33);

        Ad1.setColumns(20);
        Ad1.setFont(new java.awt.Font("LCD", 0, 18));
        Ad1.setLineWrap(true);
        Ad1.setRows(5);
        Ad1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Ad1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(270, 210, 340, 90);

        jLabel5.setFont(new java.awt.Font("LCD", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 51));
        jLabel5.setText("TO REGISTER :-");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 20, 290, 40);

        jLabel6.setFont(new java.awt.Font("LCD", 0, 24));
        jLabel6.setForeground(new java.awt.Color(51, 255, 204));
        jLabel6.setText("Address");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(150, 220, 84, 25);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__abstergo___by_0blackcell-d46zmul.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1040, 490);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-1038)/2, (screenSize.height-486)/2, 1038, 486);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        new Main().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        String Name = Nm2.getText();              // Receivinf Data from USER
        String Address = Ad1.getText();
        String PIN = PIN1.getText();
        String Ph = Ph2.getText();

        if (Name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name not Entered");
        } else if (Address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address not Entered");
        } else if (PIN.isEmpty()) {
            JOptionPane.showMessageDialog(this, "PIN not Entered");
        } else if (Ph.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ph not Entered");
        } else {
            try {                                           // Getting Connection with A_register table in mysql

                Class.forName("java.sql.DriverManager");
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();
                String query = "INSERT INTO A_Register VALUES('" + Name + "'," + Ph + ",'" + Address + "','" + PIN + "');";
                stmt.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "You are now being REGISTERED..");
                this.setVisible(false);
                new Main(Ph).setVisible(true);                                             // Transfer Phone No. to Main Frame
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"Please, Enter appropiate detail in appropiate field.");

            }

        }




    // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Nm2.setText("");            // Clears all the respective Fields.
        Ad1.setText("");
        PIN1.setText("");
        Ph2.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void PIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIN1ActionPerformed

// TODO add your handling cSode here:
    }//GEN-LAST:event_PIN1ActionPerformed

    private void Ph2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ph2KeyTyped
        boolean max = Ph2.getText().length() > 9;
        if (max) {
            evt.consume();
        }          // Limits the input upto 10 only.
    }//GEN-LAST:event_Ph2KeyTyped

    private void PIN1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PIN1KeyTyped
        boolean max = PIN1.getText().length() > 5;
        if (max) {
            evt.consume();
        }          // Limits the input upto 6 only.
    }//GEN-LAST:event_PIN1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Ad1;
    private javax.swing.JTextField Nm2;
    private javax.swing.JTextField PIN1;
    private javax.swing.JTextField Ph2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
