
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Report.java
 *
 * Created on Nov 22, 2018, 11:11:00 PM
 */

/**
 *
 * @author Prajapati
 */
public class Report extends javax.swing.JFrame {

    /** Creates new form Report */
    public Report() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        ONm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Rpt = new javax.swing.JTextArea();
        Search = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(null);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("LCD", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("Show Me Report");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ONm.setFont(new java.awt.Font("LCD", 0, 24)); // NOI18N
        ONm.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("LCD", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 255, 102));
        jLabel1.setText("Search report by :--");

        Rpt.setColumns(20);
        Rpt.setEditable(false);
        Rpt.setRows(5);
        jScrollPane1.setViewportView(Rpt);

        Search.setBackground(new java.awt.Color(0, 0, 0));
        Search.setFont(new java.awt.Font("LCD", 0, 24)); // NOI18N
        Search.setForeground(new java.awt.Color(153, 153, 255));
        Search.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cleint Name", "Officer Name", "Time(hh:mm:ss)", "Date(yyyy-mm-dd)", "Type of Case", "Pin", "Phone" }));
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("LCD", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 102, 102));
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("LCD", 0, 20)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 102, 102));
        jButton3.setText("Log out");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/__abstergo___by_0blackcell-d46zmul.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(ONm, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(370, 370, 370)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1065, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(Search, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(ONm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String R = ONm.getText();                    // User input the detail

 if(Search.getSelectedIndex()==0)
try {Rpt.setVisible(true);                        // Report Displaying Area
                Class.forName("java.sql.DriverManager");                            // Getting Connection with Report table in mysql.
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();

                String query = "SELECT * from report where name like '%"+R+"%';";
                ResultSet rs = stmt.executeQuery(query);
               if (rs.next()) {
                    String Cname = rs.getString("name");
                    String PIN = rs.getString("Pin");
                    String Address = rs.getString("Address");
                    String phone=rs.getString("Phone");
                    String Pname=rs.getString("officer_nm");
                    String Com=rs.getString("Complain_time");
                    Rpt.append ('\n'+ "---->ClientName :" + Cname + '\n' + "Address :" + Address + '\n' + PIN + '\n' + " date-time &" + Com + '\n' + "Ph:-" + phone+ '\n' + "Officer in charge :-" + Pname+'\n'+"-----------------------------------------------------------------------");
              } else {
                    JOptionPane.showMessageDialog(this, "Sorry!!!!  No Such Record Found ..");// This part is executed if no matching record is found
                }
            } catch (Exception e){}
                    else if(Search.getSelectedIndex()==1 || Search.getSelectedIndex()==5  ){
try {Rpt.setVisible(true);
                Class.forName("java.sql.DriverManager");              // Getting Connection with Report table in mysql.
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();

                String query = "SELECT * from report where Pin like '%"+R+"%' or Officer_nm like '%"+R+"%';";
                ResultSet rs = stmt.executeQuery(query);
               if (rs.next()) {
                    String Cname = rs.getString("name");
                    String PIN = rs.getString("Pin");
                    String Address = rs.getString("Address");
                    String phone=rs.getString("Phone");
                    String Pname=rs.getString("officer_nm");
                    String Com=rs.getString("Complain_time");
                    Rpt.append ('\n'+ "---->ClientName :" + Cname + '\n' + "Address :" + Address + '\n' + PIN + '\n' + " date-time &" + Com + '\n' + "Ph:-" + phone+ '\n' + "Officer in charge :-" + Pname+'\n'+"-----------------------------------------------------------------------");
              } else {
                    JOptionPane.showMessageDialog(this, "Sorry!!!!  No Such Record Found .. ");// This part is executed if no matching record is found
                }
            } catch (Exception e){}}
else if(Search.getSelectedIndex()==2 || Search.getSelectedIndex()==3  || Search.getSelectedIndex()==4){
try {Rpt.setVisible(true);
                Class.forName("java.sql.DriverManager");                          // Getting Connection with Report table in mysql.
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();

                String query = "SELECT * from report where complain_time like '%"+R+"%';" ;
                ResultSet rs = stmt.executeQuery(query);
               if (rs.next()) {
                    String Cname = rs.getString("name");
                    String PIN = rs.getString("Pin");
                    String Address = rs.getString("Address");
                    String phone=rs.getString("Phone");
                    String Pname=rs.getString("officer_nm");
                    String Com=rs.getString("Complain_time");
                     Rpt.append ('\n'+ "---->ClientName :" + Cname + '\n' + "Address :" + Address + '\n' + PIN + '\n' + " date-time &" + Com + '\n' + "Ph:-" + phone+ '\n' + "Officer in charge :-" + Pname+'\n'+"-----------------------------------------------------------------------");
              } else {
                    JOptionPane.showMessageDialog(this, "Sorry!!!!  No Such Record Found ..");// This part is executed if no matching record is found
                }
            } catch (Exception e){}}
else if(Search.getSelectedIndex()==6 ){
try {Rpt.setVisible(true);
                Class.forName("java.sql.DriverManager");                      // Getting Connection with Report table in mysql.
                Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/Abstergo", "root", "u");
                Statement stmt = (Statement) con.createStatement();

                String query = "SELECT * from report where phone like '%"+R+"%';" ;
                ResultSet rs = stmt.executeQuery(query);
               if (rs.next()) {
                    String Cname = rs.getString("name");
                    String PIN = rs.getString("Pin");
                    String Address = rs.getString("Address");
                    String phone=rs.getString("Phone");
                    String Pname=rs.getString("officer_nm");
                    String Com=rs.getString("Complain_time");
                      Rpt.append('\n'+ "---->ClientName :" + Cname + '\n' + "Address :" + Address + '\n' + PIN + '\n' + " date-time &" + Com + '\n' + "Ph:-" + phone+ '\n' + "Officer in charge :-" + Pname+'\n'+"-----------------------------------------------------------------------");
              } else {
                    JOptionPane.showMessageDialog(this, "Sorry!!!!  No Such Record Found ..");// This part is executed if no matching record is found
                }
            } catch (Exception e){}}






// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_SearchActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Rpt.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.setVisible(false);
new Main().setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
Rpt.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Report().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ONm;
    private javax.swing.JTextArea Rpt;
    private javax.swing.JComboBox Search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
